- name: start an EC2 instance
  hosts: localhost
  tasks:
    - name: Start the instance
      ec2: image=ami-018c9568 instance_type=m3.medium key_name=mykey region=us-east-1
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=webservers
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: configure for web
  hosts: webservers
  sudo: true
  tasks:
    - name: install nginx
      apt: name=nginx

