- name: Launch EC2 instances
  hosts: localhost
  tasks:

  - action:
      module: ec2
      key_name: mykey
      instance_type: c1.medium
      region: us-east-1
      image: ami-40603ad1
      count: 3
      wait: yes
      group: ['ping', 'web', 'ssh']
      instance_tags:
        Name: Staging::Webserver
        role: web
        env: staging

   - name: Output info about the instance
     debug: var=ec2
