- name: Upgrade web servers
  hosts: webservers
  user: ubuntu
  sudo: yes
  tasks:
    - name: Update apt cache and do dist-upgrade
      apt: update_cache=yes upgrade=dist

    - name: check if a reboot is required
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: False
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: reboot

 handlers:
    - name: reboot
      command: /sbin/reboot
